title: Leonarda Srdelić
permalink: /:title/
description: >- # this means to ignore newlines until "baseurl:"
url: "http://leonardasrdelic.github.io"
baseurl: "" # the subpath of your site, e.g. /blog # the base hostname & protocol for your site, e.g. http://example.com
icon: fa-solid fa-house

languages:
  - hr
  - en
defaultLang: hr
languageNames:
  hr: Hrvatski
  en: English
exclude_from_localizations: ["assets", "favicon.ico"]

# external: # shows a footer with social links - for available icons see fontawesome.com/icons
#   - title: Mail
#     icon: fa-solid fa-envelope
#     url: "mailto:leonardasrdelic@windowslive.com"
#   - title: LinkedIn
#     icon: fa-brands fa-linkedin
#     url: "https://www.linkedin.com/in/leonarda-srdelic-a2348217a/?originalSubdomain=hr"

# Za minute čitanja
wpm: 220  # riječi po minuti


google_analytics: G-MNWHH06E2E # Replace UA-XXXXX-Y with your actual GA tracking ID
environment: production

sass:
  sass_dir: _sass
  style: compressed # or expanded based on your preference

# Build settings
markdown: kramdown
theme: null  # Više ne koristite Minima kao gem-temu
plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
