encoding: utf-8
title: "Leonarda Srdelić"
author: "Leonarda Srdelić"
description: "Društvene mreže"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Naslovna"}
  - {file: "README.md", title: "O meni"}


external: # shows a footer with social links - for available icons see fontawesome.com/icons
  - title: Mail
    icon: fa-solid fa-envelope
    url: "mailto:leonarda.srdelic@ijf.hr"
  - title: LinkedIn
    icon: fa-brands fa-linkedin
    url: "https://www.linkedin.com/in/leonarda-srdelic/"
  - title: Subscribe
    icon: fa-solid fa-rss
    url: "/feed.xml"

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
